Разметка главной страницы
htmlacademy-htmlcss/820493-sedona-33 pull request #1
Opened 2022-01-26 13:57 UTC by dbelinsky

2022-01-27 15:56 UTC, ant1quar requested changes
Привет! ты неплохо справился. даже aria-label где-то расставил 👍 
Но нужно структуру немного подтюнить

2022-01-27 15:56 UTC, ant1quar commented on index.html
> +          <p class="advantage-text">Седона — не аттракцион для туристов, там течёт своя жизнь</p>
Будет легче, если эти элементы обернуть в блок. 
Так ты расположишь их слева в голубом квадрате, а изображение займет оставшееся место.
И в остальных элементах тоже

2022-01-27 15:56 UTC, ant1quar commented on index.html
> +          <img src="photo-1/jpg" alt="sedona-hotel">
класса почему-то нет

2022-01-27 15:56 UTC, ant1quar commented on index.html
> +        <p>+7 (812) 812-12-12</p>
тут нужна ссылка с href="tel:"

2022-01-27 15:56 UTC, ant1quar commented on index.html
> +        <img src="academy-logo.svg" alt="academy-logo">
и тут ссылка по тз

2022-01-27 15:56 UTC, ant1quar commented on index.html
> +          <img src="icon-3.svg" alt="presents-icon">
А тут обернуть все в блок вместе с иконкой. Иконка, кстати, должна быть в начале. хочешь order использовать?

2022-01-27 15:56 UTC, ant1quar commented on catalog.html
> +       <p>+7 (812) 812-12-12</p>
актуально и тут тоже

2022-01-27 15:56 UTC, ant1quar commented on catalog.html
> +              <a class="pagination-link" href="#">...</a>
тут ссылка не нужна

2022-01-27 15:56 UTC, ant1quar commented on catalog.html
> +              <b class="product-card-price">От 3000 ₽</b>
зачем тут <b>? скорее p

2022-01-27 15:56 UTC, ant1quar commented on catalog.html
> +              <b class="product-card-score">Рейтинг: 9,2</b>
тут тоже <b> не нужно

2022-01-27 15:56 UTC, ant1quar commented on catalog.html
> +          </a>
В макете, вроде, три кнопки. не хватает одной

2022-01-27 15:56 UTC, ant1quar commented on catalog.html
> +      </header>
Два хедера на странице это не к добру)

2022-01-27 15:56 UTC, ant1quar commented on catalog.html
> +              <a class="breadcrumbs-link" href="index.html">Главная</a>
Текста "Главная" там нет, там иконка

2022-01-27 15:56 UTC, ant1quar commented on catalog.html
> +                        Парковка
Давай это в спан обернем.

2022-01-28 09:18 UTC, dbelinsky commented on index.html
> +          <p class="advantage-text">Седона — не аттракцион для туристов, там течёт своя жизнь</p>
вот тут поправил. каждый набор элементов состоящих из текста обернул в див

2022-01-28 09:19 UTC, dbelinsky commented on index.html
> +          <img src="photo-1/jpg" alt="sedona-hotel">
не понял немного, к картинке еще класс добавить?

2022-01-28 09:21 UTC, dbelinsky commented on index.html
> +        <p>+7 (812) 812-12-12</p>
done

2022-01-28 09:29 UTC, dbelinsky commented on index.html
> +          <img src="icon-3.svg" alt="presents-icon">
в карточках, где есть иконка, поставил иконку на первое место, 
и обернул целиком в див.

2022-01-28 09:29 UTC, dbelinsky commented on index.html
> +        <img src="academy-logo.svg" alt="academy-logo">
тут поправил

2022-01-28 09:36 UTC, dbelinsky commented on catalog.html
> +       <p>+7 (812) 812-12-12</p>
done!

2022-01-28 09:38 UTC, dbelinsky commented on catalog.html
> +              <a class="pagination-link" href="#">...</a>
убрал этот Li  полсностью

2022-01-28 09:41 UTC, dbelinsky commented on catalog.html
> +              <b class="product-card-price">От 3000 ₽</b>
заменил на Р

2022-01-28 09:41 UTC, dbelinsky commented on catalog.html
> +              <b class="product-card-score">Рейтинг: 9,2</b>
тут тоже

2022-01-28 09:43 UTC, dbelinsky commented on catalog.html
> +          </a>
добавил кнопку "показать сетку"

2022-01-28 09:45 UTC, dbelinsky commented on catalog.html
> +      </header>
заменил на div

2022-01-28 09:46 UTC, dbelinsky commented on catalog.html
> +              <a class="breadcrumbs-link" href="index.html">Главная</a>
поставил ссылку ввиде картнки

2022-01-28 09:50 UTC, dbelinsky commented on catalog.html
> +                        Парковка
обернул каждый пункт списка в спан

2022-01-28 15:20 UTC, merged